import Game from "./types/Game";

export const InitialGameState: Game = {
  days: 1,
  state: "playing",
  timeTrack: [
    { time: 1, id: "T1", label: "Dawn", tokens: [] },
    { time: 2, id: "T2", label: "Morning", tokens: [] },
    {
      time: 3,
      id: "T3",
      label: "Noon",
      tokens: [{ id: "T", type: "time", name: "Player 1 Position", player: 1 }],
    },
    { time: 4, id: "T4", label: "Afternoon", tokens: [] },
    { time: 5, id: "T5", label: "Dusk", tokens: [] },
    { time: 6, id: "T6", label: "Evening", tokens: [] },
    { time: 7, id: "T7", label: "Midnight", tokens: [] },
    { time: 8, id: "T8", label: "Night", tokens: [] },
  ],
  unusedTokens: [
    { id: "T", type: "time", name: "Player 1 Time", player: 1 },
    { id: "B2", type: "bag", name: "Bag Slot 2", player: 1 },
    { id: "B3", type: "bag", name: "Bag Slot 3", player: 1 },
    { id: "B4", type: "bag", name: "Bag Slot 4", player: 1 },
    { id: "S1", type: "sack", name: "Sack 1", player: 1 },
    { id: "S2", type: "sack", name: "Sack 2", player: 1 },
    { id: "S3", type: "sack", name: "Sack 3", player: 1 },
    { id: "S4", type: "sack", name: "Sack 4", player: 1 },
    { id: "S5", type: "sack", name: "Sack 5", player: 1 },
    { id: "C3", type: "chest", name: "Chest 3", player: 1 },
    { id: "HR", type: "hand", name: "Right Hand", player: 1 },
    { id: "B1", type: "bag", name: "Bag Slot 1", player: 1 },
    { id: "C1", type: "chest", name: "Chest 1", player: 1 },
    { id: "C2", type: "chest", name: "Chest 2", player: 1 },
    { id: "HL", type: "hand", name: "Left Hand", player: 1 },
  ],
  places: [
    {
      id: "P1",
      type: "place",
      name: "The sand bank",
      description: "A calm river beach.",
      tokens: [
        {
          id: "S",
          type: "shelter",
          name: "Player 1 Shelter",
          player: 1,
        },
        {
          id: "P",
          type: "position",
          name: "Player 1 Position",
          player: 1,
        },
      ],
      actions: [
        { consume: ["T", "T", "T"], produce: ["X"], needs: ['P1'] },
        { consume: ["T"], produce: ["M"], needs: [] },
      ],
      unlocks: [],
    },
    
  ],
  items: [],
  lockedPlaces: [
    {
      id: "L1",
      type: "place",
      name: "The Forest",
      description: "A dark and foreboding forest.",
      tokens: [],
      actions: [
        { consume: ["T", "T", "T"], produce: ["I1"], needs: ['L1'] },
        { consume: ["T", "T", "T"], produce: ["X"], needs: ['L1'] },
        { consume: ["T", "T"], produce: ["M"], needs: [] },
      ],
      unlocks: ["I1"],
    },
    {
      id: "L2",
      type: "place",
      name: "The Moutain",
      description: "A rocky step stone wall.",
      tokens: [],
      actions: [
        { consume: ["T", "T", "T", "T"], produce: ["I3"], needs: ['L2'] },
        { consume: ["T", "T"], produce: ["M"], needs: [] },
      ],
      unlocks: ["I4"],
    },
    {
      id: "L3",
      type: "place",
      name: "The Dark Forest",
      description: "No sunlight reaches this forest.",
      tokens: [],
      actions: [
        { consume: ["T", "T", "T"], produce: ["I1"], needs: ['L3'] },
        { consume: ["T", "T", "T"], produce: ["X"], needs: ['L3'] },
        { consume: ["T", "T"], produce: ["M"], needs: [] },
      ],
      unlocks: ["I1"],
    },
  ],
  lockedItems: [
    {
      id: "I1",
      type: "item",
      name: "Wooden Stick",
      description: "a wooden stick that can be very useful.",
      tokens: [],
      actions: [{ consume: ["T"], produce: ["I2"], needs: [] }],
      unlocks: ["I2", "I3"],
    },
    {
      id: "I2",
      type: "item",
      name: "Wooden Hammer",
      description: "A clumsy wooden hammer.",
      tokens: [],
      actions: [{ consume: ["T", "I1"], produce: ["D1"], needs: [] }],
      unlocks: ["I3"],
    },
    {
      id: "I3",
      type: "item",
      name: "Wooden Table",
      description: "A sturdy wooden table.",
      tokens: [],
      actions: [{ consume: ["T", "I1"], produce: ["D1"], needs: [] }],
      unlocks: ["I4"],
    },
  ],
};
